# This is a config for E2B sandbox template.
# You can use template ID (oppxzdrwnrco9begdisb) or template name (vibe-nextjs-alemantrix) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-alemantrix") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-alemantrix") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-alemantrix')

team_id = "cad32946-5cc2-4d3a-b396-7ddf25e48f1f"
memory_mb = 2_048
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-alemantrix"
template_id = "oppxzdrwnrco9begdisb"
