"use client";

import { useState } from "react";
import Link from "next/link";
import "remixicon/fonts/remixicon.css";
import { PillNavbar } from "@/modules/home/ui/components/pill-navbar";
import { Footer } from "@/modules/home/ui/components/footer";
import { PricingSection } from "@/modules/home/ui/components/pricing-section";
import { useSignIn, SignedIn, SignedOut } from "@clerk/nextjs";

/* ─── FAQ Item ─────────────────────────────────────────────────────── */
const faqs = [
  {
    q: "What is a 3D website?",
    a: "A 3D website uses scroll-driven animations derived from AI-generated video frames to create a cinematic, immersive browsing experience — built entirely from a single text prompt.",
  },
  {
    q: "Can I export my 3D website to other platforms?",
    a: "Yes. Every project can be exported as a standalone ZIP containing all HTML, CSS, and assets. You can host it anywhere — Vercel, Netlify, or your own server.",
  },
  {
    q: "How do credits work for images and videos?",
    a: "Each AI generation consumes credits from your monthly allowance. Image generation costs 1 credit per frame, and video generation costs 10–20 credits depending on length and resolution.",
  },
  {
    q: "Is the content generated by Spatial cleared for commercial use?",
    a: "Yes. All plans include commercial use rights. You own the output and can publish, sell, or distribute it freely.",
  },
  {
    q: "How much technical knowledge do I need to get started?",
    a: "None. Spatial is designed for creators, not developers. If you can write a sentence, you can build a 3D website.",
  },
];

const FAQItem = ({ q, a }: { q: string; a: string }) => {
  const [open, setOpen] = useState(false);
  return (
    <div className="rounded-[8px] overflow-hidden font-inconsolata">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-4 py-3.5 text-left text-sm text-white font-[500] bg-[#272725] transition-colors"
      >
        <span>{q}</span>
        <i className={`ri-arrow-down-s-line text-white transition-transform duration-200 ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <div className="px-4 py-3 text-sm text-[#999999] bg-[#1A1A18] leading-relaxed">
          {a}
        </div>
      )}
    </div>
  );
};

/* ─── CTA Button ───────────────────────────────────────────────────── */
const GoogleCTAButton = () => {
  const { signIn, isLoaded } = useSignIn();
  const [isPending, setIsPending] = useState(false);

  const handleClick = async () => {
    if (!isLoaded || isPending) return;
    setIsPending(true);
    await signIn.authenticateWithRedirect({
      strategy: "oauth_google",
      redirectUrl: "/sso-callback",
      redirectUrlComplete: "/",
    });
  };

  return (
    <button
      onClick={handleClick}
      disabled={isPending}
      className="px-4 py-2 bg-white text-black text-sm font-[500] rounded-[8px] hover:bg-white/90 transition-colors disabled:opacity-70 font-inconsolata"
    >
      {isPending ? "Connecting..." : "Start Building"}
    </button>
  );
};

/* ─── Page ─────────────────────────────────────────────────────────── */
export default function PricingPage() {
  return (
    <div className="min-h-screen bg-[#1C1C1C] text-white">
      <PillNavbar />

      {/* Hero */}
      <section className="pt-40 pb-12 px-6 flex flex-col items-center text-center font-inconsolata">
        <h1 className="text-3xl md:text-5xl text-white font-[500] leading-[1] mb-4">
          Build 3D websites<br />with a single prompt
        </h1>
        <p className="text-sm text-[#cccccc]">
          The fastest way to go from a text prompt to a live, production-ready 3D website.
        </p>
      </section>

      {/* Pricing Cards */}
      <PricingSection />

      {/* FAQ */}
      <section className="py-20 px-6 max-w-2xl mx-auto w-full">
        <h2 className="text-[40px] text-white text-center font-inconsolata font-[500] mb-10">
          Frequently asked questions
        </h2>
        <div className="flex flex-col gap-2">
          {faqs.map((faq) => (
            <FAQItem key={faq.q} q={faq.q} a={faq.a} />
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6 flex flex-col items-center text-center font-inconsolata">
        <h2 className="text-3xl md:text-4xl text-white font-[500] mb-3">
          Build 3D websites 10x faster with AI
        </h2>
        <p className="text-sm text-[#666666] mb-8 max-w-md">
          Turn a single prompt into cinematic motion, frame sequences, and a scroll-driven 3D website. Built in minutes, ready to ship.
        </p>
        <SignedOut>
          <GoogleCTAButton />
        </SignedOut>
        <SignedIn>
          <Link
            href="/projects"
            className="px-4 py-2 bg-white text-black text-sm font-[500] rounded-[8px] hover:bg-white/90 transition-colors"
          >
            Start Building
          </Link>
        </SignedIn>
      </section>

      <Footer />
    </div>
  );
}